// check if status code is in [200, 300) by checking 3rd digit value
export const success = (status) => status / 100 == 2

const errors = {
    1021: 'Nickname already in use',
    1025: 'The given token is invalid'
}

export const getErrorMessage = (error) => {
    // error not generated by api
    if (!('code' in error)) {
        console.error(error)
        return 'Unexpected error'
    }

    // if code is not known
    if (!(error.code in errors)) {
        console.error(error)
        // return error.message
        return 'Unknown error'
    }

    return errors[error.code]
}
