name: post
services:
    db:
        image: postgres:alpine
        ports:
            - "$DB_PORT:$DB_PORT"
        environment:
            - POSTGRES_DB=$DB_NAME
            - POSTGRES_USER=$DB_USER 
            - POSTGRES_PASSWORD=$DB_PASSWORD
    front:
        build: 
            context: .
            dockerfile: web_server.Dockerfile
        ports:
            - "3000:3000"
        env_file: web_server/.env
        environment:
            - POSTGRES_USER=$DB_USER 
            - POSTGRES_PASSWORD=$DB_PASSWORD
            - CONTENT_LOCATION=/app/front
        volumes:
            - ./front:/app/front
            - ./lib:/app/lib
            - ./web_server:/app/web_server
            - /app/web_server/node_modules
    back:
        build:
            context: .
            dockerfile: back.Dockerfile
            args:
                name: back
        ports:
            - "4000:4000"
        env_file: back/.env
        environment:
            - DB_HOST=$DB_HOST
            - DB_PORT=$DB_PORT
            - DB_NAME=$DB_NAME
            - DB_USER=$DB_USER
            - DB_PASS=$DB_PASS
        volumes:
            - ./lib:/app/lib
            - ./back:/app/back
            - /app/back/node_modules
