export { router as albums_router } from './albums.js'
export { router as annotations_router } from './annotations.js'
export { router as poems_router } from './poems.js'
export { router as posts_router } from './posts.js'
export { router as users_router } from './users.js'
